# Mon Sep  2 10:54:00 PM CDT 2024

prefix = /usr/local
mandir = $(prefix)/share/man
man1dir = $(mandir)/man1

# Compiler settings - Can be customized.
CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -ggdb

# lib settings
LDFLAGS = -static -lcppunit -L/usr/local/lib/
INCLUDES = -I/usr/local/include/cppunit/
# add addtional libs here

# Makefile settings - Can be customized.
APPNAME = @@APP_NAME@@
EXT = cpp
ROOT=.
BLD=./build
OBJ=./build
SRC=./src

# compile & link for debug
#debug: CXXFLAGS += -DDEBUG -g
debug: all

# compile & link for debug GDBversion variable
#debuggdb: CXXFLAGS += -DDEBUG -ggdb # compile & link
all: $(APPNAME) bash_color_test

# link
$(APPNAME): $(APPNAME).o main.o #@@PREREQUISTE@@
	 $(CXX) $(CXXFLAGS) -o $(BLD)/$(APPNAME) $(BLD)/$(APPNAME).o $(BLD)/main.o #@@CLASS_NAME@@

# compile only
$(APPNAME).o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/$(APPNAME).$(EXT) -o $(OBJ)/$(APPNAME).o
	
main.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.$(EXT) -o $(OBJ)/main.o

bash_color_test: bash_color_test.o
	$(CXX) $(CXXFLAGS) $(BLD)/bash_color_test.o -o $(BLD)/bash_color_test

bash_color_test.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/bash_color_test.cpp -o $(OBJ)/bash_color_test.o

# install man pages
.PHONY: man
man:
	cp ../man/$(APPNAME).1 $(man1dir)
	# gzip $(man1dir)/$(APPNAME).1
	mandb

.PHONY: unman
unman:
	-rm -rf $(man1dir)/$(APPNAME).1.gz
	mandb

# install 
.PHONY: install
install: man
	cp $(BLD)/$(APPNAME) $(prefix)/bin/$(APPNAME)
	rm $(prefix)/bin/$(APPNAME)

# delete object files & app executable
.PHONY: clean
clean:
	-rm -rf $(OBJ)/*
	-rm -rf $(BLD)/*
	
# delete object files, app, executables, & all automake/autoconf generated files
.PHONY: distclean
distclean: clean
	
clean-local:
	-rm -rf config.status configure config.log
	-rm -rf autom4te.cache/
	-rm =-rf aclocal.m4
	-rm -rf compile install-sh missing Makefile.in
	
dist: 
	git archive HEAD | gzip > $(BLD)/$(APPNAME).$(BLD_VERSION).tar.gz

dist-gz: dist
