# License:    None
# File Name:  ./makefile
# Build Date: Sun May 26 10:57:08 PM CDT 2024
# Version:    0.1.0

prefix = /usr/local
mandir = $(prefix)/share/man
man1dir = $(mandir)/man1

# Compiler settings - Can be customized.
CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -ggdb
# lib settings
LDFLAGS = -static -lcppunit -L/usr/local/lib/
INCLUDES = -I/usr/local/include/cppunit/

# Makefile settings - Can be customized.
APPNAME = @@APP_NAME@@
EXT = cpp
ROOT  = .
BUILD = ./build
OBJ = ./build
SRC = ./src

all: $(APPNAME) bash_color_test

# link
$(APPNAME): $(APPNAME).o main.o @@CLASS_NAME@@ #END
	 $(CXX) $(CXXFLAGS) $(BUILD)/$(APPNAME).o $(BUILD)/main.o @@CLASS_NAME@@ -o $(BUILD)/$(APPNAME)

# compile only
$(APPNAME).o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/$(APPNAME).$(EXT) -o $(OBJ)/$(APPNAME).o

main.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.$(EXT) -o $(BUILD)/main.o
	# $(CXX) $(CXXFLAGS) $(INCLUDES) $(BUILD)/$(APPNAME).o $(LDFLAGS) -o $(BUILD)/$(APPNAME)_test

## auto gernerated here ##

# link
$(APPNAME)_test: $(APPNAME)_test.o
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(BUILD)/$(APPNAME)_test.o $(BUILD)/$(APPNAME).o $(LDFLAGS) -o $(BUILD)/$(APPNAME)_test

# compile only
$(APPNAME)_test.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/$(APPNAME)_test.cpp -o $(OBJ)/$(APPNAME)_test.o

bash_color_test: bash_color_test.o
	$(CXX) $(CXXFLAGS) $(BUILD)/bash_color_test.o -o $(BUILD)/bash_color_test

bash_color_test.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/bash_color_test.cpp -o $(OBJ)/bash_color_test.o

# install man pages
.PHONY: man
man:
	cp ../man/$(APPNAME).1 $(man1dir)
	# gzip $(man1dir)/$(APPNAME).1
	mandb

.PHONY: unman
unman:
	rm $(man1dir)/$(APPNAME).1.gz
	mandb

# install
.PHONY: install
install: man
	cp $(BUILD)/$(APPNAME) $(prefix)/bin/$(APPNAME)
	rm $(prefix)/bin/$(APPNAME)

# delete object files & app executable
.PHONY: clean
clean:
	-rm -f $(OBJ)/*.o
	-rm -f $(BUILD)/$(APPNAME)
	-rm -f $(BUILD)/$(APPNAME)_test
	-rm -f $(BUILD)/bash_color_test
	-rm -f $(BUILD)/*.xml $(BUILD)/$(APPNAME).$(BUILD_VERSION).tar.gz
	-rm -f $(BUILD)/$(APPNAME).core

# delete object files, app, executables, & all automake/autoconf generated files
.PHONY: distclean
distclean: clean
	-rm -f $(ROOT)/config.* $(ROOT)/Makefile $(ROOT)/Makefile.in $(ROOT)/INSTALL $(ROOT)/configure
	-rm -f $(ROOT)/stamp-h1 $(ROOT)/aclocal.m4 $(ROOT)/compile $(ROOT)/install-sh $(ROOT)/libtool $(ROOT)/ltmain.sh $(ROOT)/stamp-h1 $(ROOT)/missing $(ROOT)/depcomp
	-rm -f $(SRC)/Makefile $(SRC)/Makefile.in
	-rm -rf $(ROOT)/autom4te.cache $(SRC)/.deps $(SRC)/.libs

clean-local:
	-rm -f config.status configure config.log
	-rm -rf autom4te.cache/
	-rm =-f aclocal.m4
	-rm -f compile install-sh missing Makefile.in

dist:
	git archive HEAD | gzip > $(BUILD)/$(APPNAME).$(BUILD_VERSION).tar.gz

dist-gz: dist
