#!/bin/bash

INPUT=$1
CLASS_NAME=${INPUT%%::*}
BASE_CLASS_NAME=${INPUT#${CLASS_NAME}}
# Base class bug !!
BASE_CLASS_NAME=${INPUT##*::}
#BASE_CLASS_NAME=${BASE_CLASS_NAME:="NO_BASE"}


echo "CLASS_NAME=${CLASS_NAME}"
echo "BASE_CLASS_NAME=${BASE_CLASS_NAME}"