#!/bin/bash

USER_NAME=$(whoami)
USER_ROOT="/home/$USER_NAME/"
INPUT=$1
INPUT_PATH=$2
OUTPUT_PATH=$3
LICENSE=$4
AUTHOR=$5
BUILD_DATE=$6
VERSION=$7

CLASS_NAME=${INPUT%%::*}
BASE_CLASS_NAME=${INPUT##*::}

echo '${CLASS_NAME}'=${CLASS_NAME}
echo '${BASE_CLASS_NAME}'=${BASE_CLASS_NAME}

echo '${VERSION:-"VERSION_UNSET"}'=${VERSION:-"VERSION_UNSET"} # UNSET
echo '${VERSION}'=${VERSION} # UNSET

echo '${VERSION:="VERSION_UNSET"}'=${VERSION:="VERSION_UNSET"} # UNSET
echo '${VERSION}'=${VERSION} # SET

VERSION=69
echo '${VERSION:-"VERSION_UNSET"}'=${VERSION:-"VERSION_UNSET"} # SET
echo '${VERSION}'=${VERSION} # SET

#INPUT_PATH
BIN_PATH="/home/$USER_NAME/bin/"
echo '${BIN_PATH}'="${BIN_PATH}"

#OUTPUT_PATH
PROJECT_PATH="$PWD/src/${CLASS_NAME}.hpp"
echo '${PROJECT_PATH}'="${PROJECT_PATH}"
