#!/bin/bash

USER_NAME=$(whoami)
INPUT=$1
INPUT_PATH=$2
OUTPUT_PATH=$3
LICENSE=$4
AUTHOR=$5
BUILD_DATE=$6
VERSION=$7

CLASS_NAME=${INPUT%%::*}
BASE_CLASS_NAME=${INPUT##*::}

echo "CLASS_NAME=${CLASS_NAME}"
echo "BASE_CLASS_NAME=${BASE_CLASS_NAME}"

echo ${VERSION:-"VERSION_UNSET"}
echo ${VERSION} # UNSET

echo ${VERSION:="VERSION_UNSET"}
echo ${VERSION} # SET

VERSION=69
echo ${VERSION:-"VERSION_UNSET"}
echo ${VERSION}



