#!/bin/bash

APP_NAME=$1 
TEMPLATE_PATH=$2
PROJECT_PATH=$3

# defaults
DEFAULT_APP_NAME='NoName'
DEFAULT_TEMPLATE_PATH='/home/brian/src/templates/project_templates/minimal'
DEFAULT_PROJECT_PATH="/home/brian/src"

./skel.sh ${APP_NAME:-$DEFAULT_APP_NAME} ${TEMPLATE_PATH:-$DEFAULT_TEMPLATE_PATH} ${PROJECT_PATH:-$DEFAULT_PROJECT_PATH}