#// License:    None
#// File Name:  ./Makefile
#// Build Date: Tue Nov 14 04:08:48 PM CST 2023
#// Version:    0.0.1

CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -g
APPNAME = @@APP_NAME@@
BUILD = build
OBJ =  build
SRC = src

debug: all

all: @@APP_NAME@@

@@APP_NAME@@: @@APP_NAME@@.o main.o #@@PREREQUISTE@@
	 $(CXX) $(CXXFLAGS) $(BUILD)/@@APP_NAME@@.o $(BUILD)/main.o -o $(BUILD)/@@APP_NAME@@ #@@CLASS_NAME@@

@@APP_NAME@@.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/@@APP_NAME@@.cpp -o $(BUILD)/@@APP_NAME@@.o
	
main.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.cpp -o $(BUILD)/main.o

#AUTO_INSERT_POINT_DO_NOT_REMOVE#

clean:
	-rm -f $(OBJ)/*.
	-rm -f $(BUILD)/*
	