#// License:    None
#// File Name:  ./Makefile
#// Build Date: Tue Nov 14 04:08:48 PM CST 2023
#// Version:    0.0.1

CXX=g++
CXXFLAGS=-Wall -std=c++17 -DDEBUG -g
APPNAME= @@APP_NAME@@
BLD=build
OBJ=build
SRC=src

debug: all

all: $(BLD)/@@APP_NAME@@

$(BLD)/@@APP_NAME@@: $(BLD)/@@APP_NAME@@.o main.o #@@PREREQUISTE@@
	 $(CXX) $(CXXFLAGS) $(BLD)/@@APP_NAME@@.o $(BLD)/main.o -o $(BLD)/@@APP_NAME@@ #@@CLASS_NAME@@

$(BLD)/@@APP_NAME@@.o: $(SRC)/@@APP_NAME@@.cpp
	$(CXX) $(CXXFLAGS) -c $(SRC)/@@APP_NAME@@.cpp -o $(BLD)/@@APP_NAME@@.o

$(BLD)/main.o: $(SRC)/main.cpp
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.cpp -o $(BLD)/main.o

#AUTO_INSERT_POINT_DO_NOT_REMOVE#

.PHONY: clean
clean:
	-rm -f $(OBJ)/*.
	-rm -f $(BLD)/*
