# 

CXX = g++
CXXFLAGS = -Wall -std=c++17 -DDEBUG -g
APPNAME = @@APP_NAME@@
BUILD = build
OBJ =  build
SRC = src


debug: all

all: @@APPNAME@@

@@APPNAME@@: @@APPNAME@@.o main.o #@@PREREQUISTE@@
	 $(CXX) $(CXXFLAGS) $(BUILD)/@@APPNAME@@.o $(BUILD)/main.o -o $(BUILD)/@@APPNAME@@ #@@CLASS_NAME@@

@@APPNAME@@.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/@@APPNAME@@.cpp -o $(BUILD)/@@APPNAME@@.o
	
main.o:
	$(CXX) $(CXXFLAGS) -c $(SRC)/main.cpp -o $(BUILD)/main.o

#AUTO_INSERT_POINT_DO_NOT_REMOVE#

clean:
	-rm -f $(OBJ)/*.
	-rm -f $(BUILD)/*
	