# @file:  ./Makefile
# @date: Tue Nov 14 04:08:48 PM CST 2023
# @version:    0.0.1

all: reinstall

reinstall: uninstall # INSERT <?php echo("\r$DATE"); ?>
	./install.sh

install: uninstall
	./install.sh

uninstall:
	./uninstall.sh
